package fr.eql.ai116.proj2.tim.entity;
// model
enum CarModel {


    // Marques spécialisées dans les voitures électriques
    TESLA_MODEL_S,
    TESLA_MODEL_3,
    TESLA_MODEL_X,
    TESLA_MODEL_Y,
    TESLA_CYBERTRUCK,
    TESLA_SEMI,

    RIVIAN_R1T,
    RIVIAN_R1S,

    LUCID_AIR,

    BYTON_M_BYTE,

    NIO_ES8,
    NIO_ES6,
    NIO_EC6,
    NIO_ET7,

    POLestar_1,
    POLestar_2,
    POLestar_3,

    FISKER_OCEAN,
    FISKER_EMOTION,

    BOLLINGER_B1,
    BOLLINGER_B2,

    LORDSTOWN_ENDURANCE,

    FARADAY_FF_91,

    CANOO_EV,

    // Constructeurs traditionnels avec des modèles électriques
    AUDI_ETRON,
    AUDI_ETRON_GT,
    AUDI_Q4_ETRON,

    BMW_I3,
    BMW_I4,
    BMW_IX3,
    BMW_IX,

    VOLKSWAGEN_ID_3,
    VOLKSWAGEN_ID_4,
    VOLKSWAGEN_ID_BUZZ,

    MERCEDES_EQC,
    MERCEDES_EQS,
    MERCEDES_EQB,

    PORSCHE_TAYCAN,
    PORSCHE_TAYCAN_CROSS_TURISMO,

    FORD_MUSTANG_MACH_E,
    FORD_F_150_LIGHTNING,

    CHEVROLET_BOLT_EV,
    CHEVROLET_BOLT_EUV,

    HYUNDAI_IONIQ_5,
    HYUNDAI_KONA_ELECTRIC,

    KIA_SOUL_EV,
    KIA_NIRO_EV,

    NISSAN_LEAF,
    NISSAN_ARIYA,

    VOLVO_XC40_RECHARGE,
    VOLVO_C40_RECHARGE,

    PEUGEOT_E_208,
    PEUGEOT_E_2008,

    RENAULT_ZOE,
    RENAULT_MEGANE_E_TECH_ELECTRIC,

    JAGUAR_I_PACE,

    LAND_ROVER_DEFENDER_EV,
    LAND_ROVER_RANGE_ROVER_EV,

    MINI_ELECTRIC,

    MAZDA_MX_30,

    FIAT_500_ELECTRIC,

    HONDA_E,

    TOYOTA_BZ4X,

    SMART_EQ_FORTWO,

    SUBARU_SOLTERRA,

    // Marques chinoises populaires
    BYD_TANG_EV,
    BYD_QIN_EV,
    BYD_E6,

    XPENG_P7,
    XPENG_G3,

    GEELY_GEOMETRY_A,
    GEELY_GEOMETRY_C,

    SAIC_MOTOR_MG_ZS_EV,
    SAIC_MOTOR_MG5_EV,

    GREATWALL_ORA_GOOD_CAT,
    GREATWALL_ORA_FUNKY_CAT,

    LI_AUTO_LI_ONE,

    WELTMEISTER_EX5,
    WELTMEISTER_EX6,

    HONGQI_E_HS9;
}
